### ISSUE TITLE
Final group capstone - Book an Appointment

### ISSUE THREAD

**Issue by romans-adi** [romans-adi/travel-booking-backend#20]
We have 3 people in our group: @MMGGYY66 , @carreraprogrammer , @romans-adi .
Here is a [link](https://github.com/users/romans-adi/projects/2) to our project.
![image](https://github.com/romans-adi/travel-booking/assets/83185550/fdc966b5-916b-47b1-b180-27c20cd55a48)

**Comment by Meltrust** [comment]
Hi @romans-adi ,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have assignees, descriptions, and have pointings according to the spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
